/**
 * Generate CLAUDE.md file from approved rules
 */

import type { Rule } from '../types';
import { groupByCategory, formatCategory } from '../rules-formatter';

export function generateClaudeMd(rules: Rule[]): string {
  const grouped = groupByCategory(rules);

  let content = `# Claude Code Project Instructions
# Generated by Agent Orchestrator - Shared Memory System
# Last updated: ${new Date().toISOString()}

## Overview
This document contains coding rules and conventions extracted from your team's chat histories.

`;

  // Sort categories for consistent output
  const categories = Object.keys(grouped).sort();

  for (const category of categories) {
    const categoryRules = grouped[category as keyof typeof grouped];
    if (!categoryRules || categoryRules.length === 0) continue;

    content += `## ${formatCategory(category as any)}\n\n`;

    // Sort rules by confidence (highest first)
    const sortedRules = categoryRules.sort((a, b) => b.confidence_score - a.confidence_score);

    for (const rule of sortedRules) {
      content += `### ${rule.rule_text}\n\n`;
      content += `**Confidence:** ${(rule.confidence_score * 100).toFixed(0)}%\n\n`;

      // Add source context if available
      if (rule.source_session_ids && rule.source_session_ids.length > 0) {
        content += `**Derived from ${rule.source_session_ids.length} conversation(s)**\n\n`;
      }
    }

    content += '\n';
  }

  return content;
}
