"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.getMaxInputLength = exports.supportsSummaryStreaming = exports.supportsStreaming = exports.isAudioProvider = exports.isSummaryProvider = exports.isImageProvider = void 0;
var capability_checker_1 = require("./capability-checker");
Object.defineProperty(exports, "isImageProvider", { enumerable: true, get: function () { return capability_checker_1.isImageProvider; } });
Object.defineProperty(exports, "isSummaryProvider", { enumerable: true, get: function () { return capability_checker_1.isSummaryProvider; } });
Object.defineProperty(exports, "isAudioProvider", { enumerable: true, get: function () { return capability_checker_1.isAudioProvider; } });
Object.defineProperty(exports, "supportsStreaming", { enumerable: true, get: function () { return capability_checker_1.supportsStreaming; } });
Object.defineProperty(exports, "supportsSummaryStreaming", { enumerable: true, get: function () { return capability_checker_1.supportsSummaryStreaming; } });
Object.defineProperty(exports, "getMaxInputLength", { enumerable: true, get: function () { return capability_checker_1.getMaxInputLength; } });
